# This is a build for checking Pull Requests.
# It should be triggered by Azure DevOps automatically when Pull Request is created
# (you need to configure triggering in Azure DevOps by yourself).
# Parameters for this build are defined in
# - ./_settings/base.yml
# - ./_settings/base.partial.yml -- change here
# - ./_settings/pr.yml
# - ./_settings/pr.partial.yml --or change here
trigger: none
parameters:
  - name: ui_test_shards
    type: number
    default: 1
extends:
  template: azure-pipelines-template.yml
  parameters:
    name: pr
    ui_test_shards: ${{ parameters.ui_test_shards }}
