# This is a build for checking Pull Requests.
# It should be triggered by Azure DevOps automatically when Pull Request is created
# (you need to configure triggering in Azure DevOps by yourself, to do that:
# 1. Go to Branches (Repo -> Branches)
# 2. Choose `main` branch, go to Branch Policies
# 3. Add `Build Validation` step pointing it to the current file
# Parameters for this build are defined in
# - ./_settings/base.yml
# - ./_settings/base.partial.yml -- change here
# - ./_settings/pr.yml
# - ./_settings/pr.partial.yml --or change here
trigger: none
pr:
  branches:
    include:
      - '*' # Trigger on PRs targeting any branch

parameters:
  - name: sb_test_shards
    type: number
    default: 0
  - name: e2e_test_shards
    type: number
    default: 0
extends:
  template: azure-pipelines-template.yml
  parameters:
    name: pr
    sb_test_shards: ${{ parameters.sb_test_shards }}
    e2e_test_shards: ${{ parameters.e2e_test_shards }}
