# This is a build for checking Pull Requests.
# It should be triggered by Azure DevOps automatically when Pull Request is created
# (you need to configure triggering in Azure DevOps by yourself).
trigger: none
pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'webapi/MccSoft.TemplateApp.sln'
  project: 'webapi/src/MccSoft.TemplateApp.App/MccSoft.TemplateApp.App.csproj'

steps:
  - template: ./azure-pipelines-tests-shared.yml
