apiVersion: v1
kind: Secret
metadata:
  name: ${project}-secrets
  namespace: ${namespace}
type: Opaque
stringData:
  DUMMY: placeholder
# this is just a placeholder file to create the secret
# !!! Don't enter any secrets here !!!
# !!! Only edit them in the Rancher UI or CLI !!!
