version: "3.4"
services:

  integresql:
    image: allaboutapps/integresql:1.0.0
    restart: always
    depends_on:
      - postgres_internal
    ports:
      - "5000:5000"
    environment:
      PGHOST: postgres_internal
      PGUSER: postgres
      PGPASSWORD: postgres
      INTEGRESQL_TEST_MAX_POOL_SIZE: 100


  postgres_internal:
    image: pgvector/pgvector:pg17
    restart: always
    # ATTENTION
    # fsync=off, synchronous_commit=off and full_page_writes=off
    # gives us a major speed up during local development and testing (~30%),
    # however you should NEVER use these settings in PRODUCTION unless
    # you want to have CORRUPTED data.
    # DO NOT COPY/PASTE THIS BLINDLY.
    # YOU HAVE BEEN WARNED.
    # Apply some performance improvements to pg as these guarantees are not needed while running locally
    command: "postgres -c 'shared_buffers=128MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=100' -c 'client_min_messages=warning'"
    expose:
      - "5434"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
