---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-dashboards-ingress
  namespace: opensearch
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    cert-manager.io/cluster-issuer: 'letsencrypt'
    certmanager.k8s.io/acme-challenge-type: dns01
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: opensearch-stripprefix@kubernetescrd
spec:
  tls:
    - hosts:
        - 'logs.mcc-soft.de'
      secretName: opensearch-cert
  rules:
    - host: 'logs.mcc-soft.de'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-dashboards
                port:
                  name: http
          - path: /data
            pathType: Prefix
            backend:
              service:
                name: opensearch
                port:
                  name: opensearch-data
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: opensearch
spec:
  stripPrefix:
    prefixes:
      - /data
